name = "DiseaseInitiation"
uuid = "6b3d34e4-6e78-4b16-9484-89adcb8ef887"
version = "0.1.0"

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BlackBoxOptim = "0.6.3"
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
LinearAlgebra = "1.11.0"
Statistics = "1.11.1"
