name = "DiseaseInitiation"
uuid = "6b3d34e4-6e78-4b16-9484-89adcb8ef887"
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
LinearAlgebra = "1.11.0"
